version: '3'

services:
  rails:
    image: 1080tic/chatwoot:latest
    build:
      context: .
      dockerfile: Dockerfile.1080tic
    env_file: .env
    depends_on:
      - postgres
      - redis
    ports:
      - 3000:3000
    volumes:
      - ./storage:/app/storage
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
      - INSTALLATION_ENV=docker
      - INSTALLATION_NAME=1080 TIC
      - BRAND_NAME=1080 TIC
    command: ['bundle', 'exec', 'rails', 's', '-p', '3000', '-b', '0.0.0.0']
    restart: unless-stopped

  sidekiq:
    image: 1080tic/chatwoot:latest
    env_file: .env
    depends_on:
      - postgres
      - redis
    volumes:
      - ./storage:/app/storage
    environment:
      - NODE_ENV=production
      - RAILS_ENV=production
    command: ['bundle', 'exec', 'sidekiq', '-C', 'config/sidekiq.yml']
    restart: unless-stopped

  postgres:
    image: pgvector/pgvector:pg16
    restart: always
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=chatwoot_prod
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=chatwoot_db_pass_2024

  redis:
    image: redis:alpine
    restart: always
    command: ["sh", "-c", "redis-server --requirepass \"$$REDIS_PASSWORD\""]
    environment:
      - REDIS_PASSWORD=chatwoot_redis_pass_2024
    volumes:
      - redis:/data
    ports:
      - '6379:6379'

volumes:
  postgres:
  redis:
